### PR TITLE
Add a simple Websocket client example site

### PR DESCRIPTION
**Pull request by rkrzr**
Add a simple JS example listener.

### CODE REVIEW

**Comment by ruuda** [comment]
Helvetica or not, I think an opening `<html>` tag might be appropriate.

**Comment by arianvp** [comment]
Nope it's not required by the html5 spec

**Comment by ruuda** [comment]
TIL. A `<div>` inside a `<p>` is not allowed though. You can use a `<span>` instead.

**Comment by rkrzr** [comment]
Thanks for correcting my HTML and style violations. That Helvetica really makes all the difference @duijf !
I'll try to use more JS dependencies next time.

**Pull request merged**
