### PR TITLE
Prefix all server modules with Icepeak.Server

### LINKED ISSUE #108: Change namespace for server modules
In order to publish the package on Hackage, we should have some consistency between client and server, and we should change the server namespace to `Icepeak.Server.*`.

### PR DESCRIPTION
**Pull request by robbert-vdh**
This is needed before icepeak can be published to Hackage and used as a library in other applications without causing conflicts.

Resolves #108.

### CODE REVIEW

**Review by DiegoDiverio — APPROVED** [review]
It looks good to me, and the CI is happy! `emacs` even added newlines when it felt the need for it :)

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @robbert-vdh, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as bf42b1e28170d10fae9c00c1650730e248bc8c0f, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/286197b5-a831-4751-bc13-37a9c950fa4c?pipeline_id=ae16ca4a-691b-42de-8483-7abc85095eeb) started.

**Pull request merged**
