### PR TITLE
ci: machine type from e1 to f1

### PR DESCRIPTION
**Pull request by d-goncalves**

### CODE REVIEW

**Comment by d-goncalves** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as cfcb326fd88bbecda40644817a1ecd818d37f4bc, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/9fc27d2b-a284-415d-bd1d-c2111bab4315?pipeline_id=bfec2b91-ede1-413d-9280-c12345c9a1fb) started.

**Pull request merged**
