### PR TITLE
Upgrade stack from LTS 19.17 to 19.32

### PR DESCRIPTION
**Pull request by rkrzr**
And remove some unused imports. There were no code changes required.

### CODE REVIEW

**Review by xrvdg — APPROVED** [review]
LGTM!

**Comment by rkrzr** [comment]
@OpsBotPrime merge

**Comment by alex-mckenna** [comment]
@rkrzr I don't think OpsBotPrime listens to this repo? The previous PRs seem to have been manually merged

**Comment by rkrzr** [comment]
Haha, indeed, seems like it. Will merge manually.

**Pull request merged**
