### PR TITLE
Update nixpkgs pin

### PR DESCRIPTION
**Pull request by crtschin**
PR makes the following changes:
- Updates the nixpkgs pin,
  - Regenerated the `.cabal.freeze` file and bounds using `cabal gen-bounds`
  - Hashable was updated, changing the order when converted to a list. I added a sort operation on the affected tests.
  - Added fourmolu pre-filled with our preferred parameters.
- Drive-by change to use aeson's capability to directly output `ByteString` instead of using `Value` as an intermediary.

### CODE REVIEW

**Review by robbert-vdh — APPROVED** [review]
LGTM, thanks for doing this!

**Comment by crtschin** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @crtschin, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 521d1c9e60dcaf362fda63e051d4e93a5e203d31, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/2267c28f-d734-455a-ae22-daae8cb68d44?pipeline_id=796fa915-4ad8-435c-ae89-6d4f00b2fe0e) started.

**Pull request merged**
