### PR TITLE
Add RELEASE.md to describe release process

### PR DESCRIPTION
**Pull request by DiegoDiverio**
I added a very basic RELEASE.md file (to be improved if needs be) to describe how we should release new versions of Icepeak.

### CODE REVIEW

**Review by fatho — APPROVED** [review]
Thanks!

**Comment by DiegoDiverio** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DiegoDiverio, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 73da8e6bed9be9d24427da9e71a44d080b0abf9a, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/9c025ed6-faa2-4459-9ccd-7ec64335857d?pipeline_id=65a70ba6-f3d9-458c-bed6-b38b43027c00) started.

**Pull request merged**
